"""
visualization.py
----------------
This module visualizes the traffic junction using Pygame.
It reads vehicle data from lane files generated by traffic_generator.py
and displays vehicle count and traffic lights in real time.
"""

import pygame
import os
import time

# ---------------- CONFIG ---------------- #

WIDTH, HEIGHT = 800, 800
BG_COLOR = (245, 245, 220)
ROAD_COLOR = (128, 128, 128)
LANE_COLOR = (25, 50, 255)
TEXT_COLOR = (255, 255, 255)

GREEN = (0, 200, 0)
RED = (200, 0, 0)

ROADS = ["A", "B", "C", "D"]
LANES = ["L1", "L2", "L3"]

FONT_SIZE = 20
REFRESH_DELAY = 1  # seconds

# --------------------------------------- #


def read_lane_count(road, lane):
    """
    Reads the number of vehicles in a lane file.
    """
    filename = f"{road}{lane}.txt"
    if not os.path.exists(filename):
        return 0

    with open(filename, "r") as f:
        return len(f.readlines())


def draw_text(screen, text, x, y, font):
    """
    Draws text on the screen.
    """
    img = font.render(text, True, TEXT_COLOR)
    screen.blit(img, (x, y))


def visualize():
    pygame.init()
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    pygame.display.set_caption("Traffic Junction Visualization")

    font = pygame.font.SysFont(None, FONT_SIZE)
    clock = pygame.time.Clock()

    running = True

    while running:
        screen.fill(BG_COLOR)

        # ---------------- EVENT HANDLING ---------------- #
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        # ---------------- DRAW JUNCTION ---------------- #

        # Vertical road
        pygame.draw.rect(screen, ROAD_COLOR, (350, 0, 100, 800))

        # Horizontal road
        pygame.draw.rect(screen, ROAD_COLOR, (0, 350, 800, 100))

        # ---------------- DISPLAY LANE COUNTS ---------------- #

        # Road A (Top)
        draw_text(screen, "Road A", 360, 20, font)
        draw_text(screen, f"L1: {read_lane_count('A','L1')}", 360, 50, font)
        draw_text(screen, f"L2: {read_lane_count('A','L2')}", 360, 75, font)
        draw_text(screen, f"L3: {read_lane_count('A','L3')}", 360, 100, font)

        # Road B (Right)
        draw_text(screen, "Road B", 520, 360, font)
        draw_text(screen, f"L1: {read_lane_count('B','L1')}", 520, 390, font)
        draw_text(screen, f"L2: {read_lane_count('B','L2')}", 520, 415, font)
        draw_text(screen, f"L3: {read_lane_count('B','L3')}", 520, 440, font)

        # Road C (Bottom)
        draw_text(screen, "Road C", 360, 520, font)
        draw_text(screen, f"L1: {read_lane_count('C','L1')}", 360, 550, font)
        draw_text(screen, f"L2: {read_lane_count('C','L2')}", 360, 575, font)
        draw_text(screen, f"L3: {read_lane_count('C','L3')}", 360, 600, font)

        # Road D (Left)
        draw_text(screen, "Road D", 120, 360, font)
        draw_text(screen, f"L1: {read_lane_count('D','L1')}", 120, 390, font)
        draw_text(screen, f"L2: {read_lane_count('D','L2')}", 120, 415, font)
        draw_text(screen, f"L3: {read_lane_count('D','L3')}", 120, 440, font)

        pygame.display.update()
        time.sleep(REFRESH_DELAY)
        clock.tick(60)

    pygame.quit()


if __name__ == "__main__":
    visualize()
